#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v19
# autospec commit: 6a4b23bb3e69
#
Name     : azure-macro-utils-c
Version  : bb156d99fc966a3ee6e4155947ade1e32b73c89f
Release  : 2
URL      : https://github.com/Azure/macro-utils-c/archive/bb156d99fc966a3ee6e4155947ade1e32b73c89f/azure-macro-utils-c-bb156d99fc966a3ee6e4155947ade1e32b73c89f.tar.gz
Source0  : https://github.com/Azure/macro-utils-c/archive/bb156d99fc966a3ee6e4155947ade1e32b73c89f/azure-macro-utils-c-bb156d99fc966a3ee6e4155947ade1e32b73c89f.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: azure-macro-utils-c-data = %{version}-%{release}
Requires: azure-macro-utils-c-license = %{version}-%{release}
BuildRequires : buildreq-cmake
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# Microsoft Azure IoT SDKs - macro utils for C
This repository contains the following:
* **a generation tool for macro_utils.h** to regenerate the file macro_utils.h. Pressing F5 after opening .sln file will regenerate macro_utils.h
* **macro_utils.h** a C header file that contains a multitude of very useful C macros

%package data
Summary: data components for the azure-macro-utils-c package.
Group: Data

%description data
data components for the azure-macro-utils-c package.


%package dev
Summary: dev components for the azure-macro-utils-c package.
Group: Development
Requires: azure-macro-utils-c-data = %{version}-%{release}
Provides: azure-macro-utils-c-devel = %{version}-%{release}
Requires: azure-macro-utils-c = %{version}-%{release}

%description dev
dev components for the azure-macro-utils-c package.


%package license
Summary: license components for the azure-macro-utils-c package.
Group: Default

%description license
license components for the azure-macro-utils-c package.


%prep
%setup -q -n macro-utils-c-bb156d99fc966a3ee6e4155947ade1e32b73c89f
cd %{_builddir}/macro-utils-c-bb156d99fc966a3ee6e4155947ade1e32b73c89f

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1726265831
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake ..   -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1726265831
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/azure-macro-utils-c
cp %{_builddir}/macro-utils-c-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/azure-macro-utils-c/47e4690f60befa1918e5ac38723973fe4cf04e9b || :
export GOAMD64=v2
GOAMD64=v2
pushd clr-build
%make_install
popd
## install_append content
# Move cmake files to a useful path
mkdir -p %{buildroot}/usr/share/cmake/%{name}
mv %{buildroot}/usr/cmake/*.cmake %{buildroot}/usr/share/cmake/%{name}
## install_append end

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/cmake/*

%files dev
%defattr(-,root,root,-)
/usr/include/macro_utils/macro_utils.h
/usr/include/macro_utils/macro_utils_generated.h

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/azure-macro-utils-c/47e4690f60befa1918e5ac38723973fe4cf04e9b
